"use client";

import React, { useEffect, useState } from 'react';
import MainLayout from '@/components/MainLayout';
import { 
  Zap, 
  BarChart3, 
  PieChart, 
  AlertCircle,
  Clock,
  ChevronRight,
  TrendingUp,
  Download
} from 'lucide-react';
import { fetchInsights } from '@/lib/api';

export default function InsightsPage() {
  const [insights, setInsights] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchInsights().then(data => {
      setInsights(data);
      setLoading(false);
    }).catch(err => {
      console.error(err);
      setLoading(false);
    });
  }, []);

  return (
    <MainLayout>
      <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
        <header className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-display font-bold text-on-background tracking-tight">AI Insights</h1>
            <p className="text-on-background/50 font-medium">Deep-dive analysis generated by the Nexus AI Core.</p>
          </div>
          <div className="flex gap-3">
            <button className="px-4 py-2 rounded-lg border border-outline/20 text-xs font-bold hover:bg-surface transition-colors flex items-center gap-2">
              <Download className="w-4 h-4" />
              Export Reports
            </button>
            <button className="px-5 py-2.5 rounded-lg gradient-cta text-white font-bold text-sm shadow-lg shadow-primary/20 hover:scale-[1.02] transition-transform flex items-center gap-2">
              <Sparkles className="w-4 h-4" />
              Generate New Insight
            </button>
          </div>
        </header>

        {loading ? (
          <div className="flex items-center justify-center h-64">
            <div className="w-12 h-12 border-4 border-primary border-t-transparent rounded-full animate-spin" />
          </div>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            <div className="lg:col-span-2 space-y-6">
              <h2 className="text-lg font-display font-bold text-on-background flex items-center gap-2">
                <Zap className="w-5 h-5 text-primary" />
                Active Intelligence Stream
              </h2>
              
              <div className="space-y-4">
                {insights.map((insight) => (
                  <div key={insight.id} className="bg-surface rounded-2xl border border-outline/10 tonal-lift p-6 group hover:border-primary/20 transition-all duration-300">
                    <div className="flex gap-6">
                      <div className={`w-12 h-12 rounded-xl flex items-center justify-center shrink-0 ${
                        insight.severity === 'high' ? 'bg-red-50 text-red-500' : 
                        insight.severity === 'medium' ? 'bg-orange-50 text-orange-500' : 'bg-blue-50 text-blue-500'
                      }`}>
                        {insight.severity === 'high' ? <AlertCircle className="w-6 h-6" /> : 
                        insight.severity === 'medium' ? <TrendingUp className="w-6 h-6" /> : <BarChart3 className="w-6 h-6" />}
                      </div>
                      <div className="flex-1 space-y-2">
                        <div className="flex items-center justify-between">
                          <h3 className="text-lg font-bold group-hover:text-primary transition-colors">{insight.title}</h3>
                          <span className="text-[10px] font-bold opacity-30 uppercase">{insight.time}</span>
                        </div>
                        <div className="flex items-center gap-4 text-xs font-semibold">
                          <span className="text-primary bg-primary/5 px-2 py-1 rounded-md">{insight.dataset}</span>
                          <span className={insight.severity === 'high' ? 'text-red-500' : 'text-on-background/40'}>
                            Priority: {insight.severity.toUpperCase()}
                          </span>
                        </div>
                        <p className="text-sm text-on-background/60 leading-relaxed font-medium">
                          {insight.summary}
                        </p>
                        <button className="text-xs font-bold text-primary flex items-center gap-1 pt-2 hover:gap-2 transition-all">
                          View Detailed Analysis <ChevronRight className="w-3 h-3" />
                        </button>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="space-y-8">
              <div className="bg-surface rounded-2xl border border-outline/10 tonal-lift p-8 glass overflow-hidden relative">
                <h2 className="text-lg font-display font-bold mb-6 flex items-center gap-2">
                  <PieChart className="w-5 h-5 text-primary" />
                  Distribution
                </h2>
                <div className="aspect-square w-full rounded-full border-[16px] border-primary/5 relative flex items-center justify-center">
                  <div className="text-center">
                    <span className="text-3xl font-display font-bold block">84%</span>
                    <span className="text-[10px] font-bold opacity-40 uppercase">Confidence</span>
                  </div>
                  <div className="absolute inset-0 rounded-full border-[16px] border-primary border-t-transparent border-l-transparent rotate-45" />
                </div>
                <div className="mt-8 space-y-3">
                  <div className="flex items-center justify-between text-xs font-bold">
                    <span className="flex items-center gap-2"><div className="w-2 h-2 rounded-sm bg-primary" /> Statistical</span>
                    <span className="opacity-40">62%</span>
                  </div>
                  <div className="flex items-center justify-between text-xs font-bold">
                    <span className="flex items-center gap-2"><div className="w-2 h-2 rounded-sm bg-primary/40" /> Predictive</span>
                    <span className="opacity-40">28%</span>
                  </div>
                  <div className="flex items-center justify-between text-xs font-bold">
                    <span className="flex items-center gap-2"><div className="w-2 h-2 rounded-sm bg-primary/20" /> Anomaly</span>
                    <span className="opacity-40">10%</span>
                  </div>
                </div>
              </div>

              <div className="bg-primary rounded-2xl p-8 text-white tonal-lift overflow-hidden relative group">
                <Zap className="absolute -right-4 -bottom-4 w-32 h-32 opacity-10 group-hover:rotate-12 transition-transform duration-500" />
                <h3 className="text-lg font-display font-bold mb-2">Automate Tasks</h3>
                <p className="text-sm opacity-80 leading-relaxed mb-6 font-medium">Let Nexus AI handle routine data cleaning and preparation automatically.</p>
                <button className="w-full py-3 bg-white text-primary rounded-xl text-xs font-bold hover:bg-opacity-90 transition-all">
                  Enable Auto-Pilot
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </MainLayout>
  );
}

function Sparkles(props: any) {
  return (
    <svg 
      {...props}
      xmlns="http://www.w3.org/2000/svg" 
      width="24" 
      height="24" 
      viewBox="0 0 24 24" 
      fill="none" 
      stroke="currentColor" 
      strokeWidth="2" 
      strokeLinecap="round" 
      strokeLinejoin="round"
    >
      <path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z"/>
      <path d="M5 3v4"/>
      <path d="M19 17v4"/>
      <path d="M3 5h4"/>
      <path d="M17 19h4"/>
    </svg>
  );
}
